services:
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app/app:cached
      - ./db:/usr/src/app/db:cached
      - ./scripts:/usr/src/app/scripts:cached
    working_dir: /usr/src/app
    command: bash -c "./scripts/run.sh"
    ports:
      - "8000:8000"
    networks:
      - fastapi_network
    env_file:
      - .env
  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fastapi_network
    env_file:
      - .env

volumes:
  db_data:
    driver: local

networks:
  fastapi_network:
    driver: bridge
    external: true